# ----> Image Intermediate
FROM cgr.dev/chainguard/python:latest-dev as builder

WORKDIR /builder

COPY requirements.txt  ./
RUN pip install -r requirements.txt --user

# ----> Image Finaly
FROM cgr.dev/chainguard/python:latest

LABEL MAINTAINER="murillogomes@giropopsapp.senhas"
ARG REDIS_HOST="redis"

WORKDIR /usr/src/app

COPY --from=builder /home/nonroot/.local/lib/python3.12/site-packages /home/nonroot/.local/lib/python3.12/site-packages
COPY static ./static/
COPY templates ./templates/
COPY app.py ./ 

ENV  REDIS_HOST=${REDIS_HOST}

EXPOSE 5000/tcp
ENTRYPOINT ["python", "-m", "flask", "run", "--host=0.0.0.0"]
